services:
  frontend:
    build:
      context: front-end
    ports:
      - 3000:3000
    expose:
      - 3000
    
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    expose:
      - 8000
